version: '3'

services:
  postgres:
    image: 'postgres:latest'

    ports:
      - 5432:5432

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DATABASE}

    volumes:
      - ./db-data/:/var/lib/postgresql/data/
